
public enum WeatherIcon {
    SUNNY, SNOW, FAIR, CLOUDY, SUNNY_INTERVALS, PARTLY_CLOUDY, RAIN, THUNDERSTORMS, FINE, FOG, CLEAR, COOL, SHOWERS, SUNNY_PERIODS,
    ISOLATED_SHOWERS, MOSTLY_CLOUDY, DUST
}
